# Generated by Django 3.2.7 on 2023-08-29 02:53

import backend.api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday_year', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday_month', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday_day', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.IntegerField(default=1)),
                ('wedding', models.IntegerField(default=1)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('hobby', models.CharField(blank=True, max_length=50, null=True)),
                ('child', models.BooleanField(default=False)),
                ('salary', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('aeb42937-a096-4bc5-a218-fade9d713261'), editable=False, primary_key=True, serialize=False)),
                ('videoId', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=backend.api.models.upload_thumbnail)),
                ('video', models.FileField(blank=True, null=True, upload_to=backend.api.models.upload_video)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvatarModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('filename', models.FileField(upload_to=backend.api.models.upload_avatar)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
