# Generated by Django 3.2.7 on 2023-08-29 02:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a5e44e99-8df0-4b04-a816-b83112894bcc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
